ï»¿{{ config(materialized='view', schema='stg') }}

select
  cast(id as String)                         as bonus_id,
  cast(user_id as String)                    as user_id,
  {{ amount_to_decimal('amount') }}          as amount,
  {{ amount_to_decimal('amount_won') }}      as amount_won,
  {{ amount_to_decimal('amount_remaining') }} as amount_remaining,
  {{ amount_to_decimal('amount_finished') }}  as amount_finished,
  cast(wager_multiplier as Int32)            as wager_multiplier,
  {{ amount_to_decimal('wager_remaining') }} as wager_remaining,
  referral_percent,
  cast(referral_id as Int32)                 as referral_id,
  cast(deposit_id as String)                 as deposit_id,
  cast(is_viewed as UInt8)                   as is_viewed,
  {{ epoch_to_dt64('from_time') }}           as from_time,
  {{ epoch_to_dt64('to_time') }}             as to_time,
  freespin_template_id, betby_template_id, betby_bonus_id,
  rule_id, promocode_id,
  {{ epoch_to_dt64('activation_date') }}     as activation_date,
  {{ epoch_to_dt64('consumed_date') }}       as consumed_date,
  {{ epoch_to_dt64('created_date') }}        as created_date,
  {{ norm_upper('type') }}                   as bonus_type,
  {{ norm_upper('status') }}                 as status,
  {{ norm_upper('wager_source') }}           as wager_source,
  {{ norm_upper('give_type') }}              as give_type,
  freespin_s_template_id, freespin_op_template_id,
  {{ epoch_to_dt64('bonus_period_from') }}   as bonus_period_from,
  {{ epoch_to_dt64('bonus_period_to') }}     as bonus_period_to,
  {{ epoch_to_dt64('expired_at') }}          as expired_at,
  wager_turnover_seconds,
  cast(is_active as UInt8)                   as is_active,
  parent_bonus_id, bet_type, min_bet_count,
  min_coefficient_express, min_coefficient_ordinary,
  return_id, title, fortune_bonus_id, localization_key,
  bonus_template_id, final_transaction, uuid, freespin_iog_template_id,
  _peerdb_synced_at
from {{ raw_src('bonuses') }}

